### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Mordag** [Mordag/api-service#1]
- [ ] Create dynamic web service
- [ ] Create service tomcat connection
- [ ] Configure server to hold files which can be opened via .../db.sql.
- [ ] Insert content into database via external database creator
- [ ] Create API calls which responds via JSON objects
